"""Changed lazy argument to select for city field in Temperature model

Revision ID: 3773da0df475
Revises: 732071908f97
Create Date: 2024-10-07 12:56:24.814227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3773da0df475'
down_revision: Union[str, None] = '732071908f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
