"""Changed argument of city field in Temperature model

Revision ID: 70fdecd017c6
Revises: 9e4028b4be4b
Create Date: 2024-10-07 12:52:55.049779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fdecd017c6'
down_revision: Union[str, None] = '9e4028b4be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
