"""Added temperature fieald to City model

Revision ID: 9e4028b4be4b
Revises: 0fec56adaa71
Create Date: 2024-10-07 12:49:07.667613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4028b4be4b'
down_revision: Union[str, None] = '0fec56adaa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
